#! /bin/sh
rm -rf ./src/*.dylib
rm -rf ./src/*.so*
rm -rf ./src/*.a
rm -rf ./src/*.dll
rm -rf ./src/*.o
rm -rf ./src/stan_files/*.o
rm -rf ./src/*.d
rm -rf ./src/*.rc
rm -rf ./src/*.rds
rm -rf ./src-*
